* [Google Keep](https://keep.google.com/u/0/#home)
* [Sprained AC Joint? 7 Things You Need To Know... | Precision Movement](https://www.precisionmovement.coach/sprained-ac-joint/)
* [Så här tränar du din piriformismuskel. – Mickes plats på nätet](http://micke.astner.se/2013/05/21/sa-har-tranar-du-din-piriformismuskel/)
* [4 Tests to Differentiate Shoulder Impingement and AC Joint Dysfunction - YouTube](https://www.youtube.com/watch?v=am0-6R-ceEs)
* [(12) 4 Tests to Differentiate Shoulder Impingement and AC Joint Dysfunction - YouTube](https://www.youtube.com/watch?v=am0-6R-ceEs)
* [Piriformis from the Runner's Angle | RunnerClick](https://runnerclick.com/piriformis/)
* [The Only 5 Exercises You Need to Get Stronger with Kettlebells - YouTube](https://www.youtube.com/watch?v=-vkZLdPUpuo)
