* [Research Data MANTRA](https://mantra.edina.ac.uk/)
* [psf/black: The uncompromising Python code formatter](https://github.com/psf/black)
* [google/yapf: A formatter for Python files](https://github.com/google/yapf#knobs)
* [FastText sentiment analysis for tweets: A straightforward guide](https://towardsdatascience.com/fasttext-sentiment-analysis-for-tweets-a-straightforward-guide-9a8c070449a2)
* [👨‍💻🤖 The 3 best auto formatters for Python - DEV Community 👩‍💻👨‍💻](https://dev.to/igeligel/the-3-best-auto-formatters-for-python-432p)
* [Interactive GIS in Jupyter with ipyleaflet - Jupyter Blog](https://blog.jupyter.org/interactive-gis-in-jupyter-with-ipyleaflet-52f9657fa7a)
* [Rosa Bonheur - Wikipedia](https://en.wikipedia.org/wiki/Rosa_Bonheur#/media/File:Rosa_Bonheur_-_Ploughing_in_Nevers_-_Google_Art_Project.jpg)
* [Happy Brothers - Wikipedia](https://en.wikipedia.org/wiki/Happy_Brothers#/media/File:Merry_brothers_1887.jpg)
* [Are These The 43 Funniest GIFs Of All Time?](https://www.buzzfeed.com/richardhjames/are-these-the-funniest-gifs-of-all-time)
* [Nix manual](https://nixos.org/nix/manual/#chap-introduction)
* [ward clustering python - Sök på Google](https://www.google.com/search?q=ward%20clustering%20python&ie=utf-8&oe=utf-8&aq=t&authuser=0)
* [Hierarchical Clustering with Python and Scikit-Learn](https://stackabuse.com/hierarchical-clustering-with-python-and-scikit-learn/)
* [DARE - Delivering Agile Research Excellence on European e-Infrastructures](http://project-dare.eu/)
* [33+26 most popular GitHub JS repositories in August and September 2019](https://itnext.io/33-26-most-popular-github-js-repositories-in-august-and-september-2019-e8f17da6af4)
* [PowerPoint Presentation](http://project-dare.eu/wp-content/uploads/2018/02/DARE_presentation_EUDAT_Semantic-Services_EOSC_23.1.2018.pdf)
* [Chocolatey Software | Chocolatey - The package manager for Windows](https://chocolatey.org/)
* [TWC9: .NET Conf, .NET Core 3.0 RC1, Cascadia Code Font, Sega Genesis Mini and more | This Week On Channel 9 | Channel 9](https://channel9.msdn.com/Shows/This+Week+On+Channel+9/TWC9-NET-Conf-NET-Core-30-RC1-Cascadia-Code-Font-Sega-Genesis-Mini-and-more)

* [Making Your Code Citable · GitHub Guides](https://guides.github.com/activities/citable-code/)
* [rezakj/scSeqR: scSeqR (Single Cell Sequencing R package) is an interactive R package to works with high-throughput single cell sequencing technologies (i.e scRNA-seq, scVDJ-seq and CITE-seq). As some research studies require a more attuned forms of normalization or spike-in normalization in some cases, scSeqR allows the users to chose from multiple normalization methods and correcting for dropouts (nonzero events counted as zero). Because some of the cell types are more challenging to work with, scSeqR also allows the users to choose from different clustering algorithms (i.e. ward.D, kmeans, ward.D2, hierarchical, etc.) and indexing methods (i.e. silhouette, ccc, kl, gap-stats, etc.) to adjust for sensitivity and stringency in order to find less or more subpopulations of cell types to design both unsupervised and supervised models to best suit your research. scSeqR provides 2D and 3D interactive visualizations, differential expression analysis, filters based on cells and genes, cell helth and cell cycle, merging, normalizing for dropouts and batch differences, pathway analysis, cell type prediction and tools to find marker genes for clusters and conditions. scSeqR inputs single cell data in 10X format, large numeric matrix files and data frames.](https://github.com/rezakj/scSeqR)
* [TOP IDE index](https://pypl.github.io/IDE.html)
* [ahejlsberg (Anders Hejlsberg)](https://github.com/ahejlsberg)
* [Home | King's Digital Lab](https://www.kdl.kcl.ac.uk/)
* [jellyfish · PyPI](https://pypi.org/project/jellyfish/)
* [myCompiler - Run your favourite programming languages online | Product Hunt](https://www.producthunt.com/posts/mycompiler)
* [Shell folder shortcuts - Windows CMD - SS64.com](https://ss64.com/nt/shell.html)
* [Axios](https://www.axios.com/)
* [Top 5 Frameworks / React UI Component Libraries for 2019](https://devias.io/blog/top-5-react-ui-component-libraries-frameworks)
* [The Greatest Ever Infographic - Numberphile - YouTube](https://www.youtube.com/watch?v=3T7jMcstxY0)
* [Mapping JSON to objects using Automapper | Coding Canvas](https://codingcanvas.com/mapping-json-to-objects-using-automapper/)
* [Shared Context between Tests > xUnit.net](https://xunit.net/docs/shared-context.html)
* [Reimagining Plutarch with NLP: Part 2 - Towards Data Science](https://towardsdatascience.com/reimagining-plutarch-with-nlp-part-2-dc4e360baa68)
* [Best Python practices for Data Scientists - Towards Data Science](https://towardsdatascience.com/best-python-practices-for-data-scientists-11056edda8c7)
* [Blog | Precision Movement](https://www.precisionmovement.coach/blog/)
* [Serializing Entity Framework objects to JSON in ASP.NET Web API | StrathWeb. A free flowing web tech monologue.](https://www.strathweb.com/2012/03/serializing-entity-framework-objects-to-json-in-asp-net-web-api/)
* [Quotium | 9 Principles (building blocks) of DSDM – AGILE](http://www.quotium.com/performance/9-principles-building-blocks-dsdm-agile/)
* [BlueStacks - Not Another Android Emulator - 6x Faster Than Any Phone](https://www.bluestacks.com/)
* [Van_Eyck_-_Arnolfini_Portrait.jpg (3087×4226)](https://upload.wikimedia.org/wikipedia/commons/3/33/Van_Eyck_-_Arnolfini_Portrait.jpg)

* [Vagrant by HashiCorp](https://www.vagrantup.com/)
* [Gensim Topic Modeling - A Guide to Building Best LDA models](https://www.machinelearningplus.com/nlp/topic-modeling-gensim-python/)
* [» The Details: Training and Validating Big Models on Big Data Journal of Digital Humanities](http://journalofdigitalhumanities.org/2-1/the-details-by-david-mimno/)
* [Ant Design of React - Ant Design](https://ant.design/docs/react/introduce?ref=devias-io)
* [Dynamic systems development method - Wikipedia](https://en.wikipedia.org/wiki/Dynamic_systems_development_method)
* [Material-UI: A popular React UI framework](https://material-ui.com/)
* [Designers · Evergreen](https://evergreen.segment.com/for-designers/)
* [mobxjs/mobx: Simple, scalable state management.](https://github.com/mobxjs/mobx)
* [.net - Using Automapper to Copy Properties from a Dynamic - Stack Overflow](https://stackoverflow.com/questions/38394587/using-automapper-to-copy-properties-from-a-dynamic)
* [filipw/dotnet-script: Run C# scripts from the .NET CLI.](https://github.com/filipw/dotnet-script)
* [How To Run Voice Activated Google Assistant on Windows PC - TechieLeaf](http://www.techieleaf.net/how-to-run-voice-activated-google-assistant-on-windows-pc/)
* [StrathWeb. A free flowing web tech monologue.](https://www.strathweb.com/)
* [EF.Core.IssueSample/ItemRepositoryTests.cs at f67e4cae02abc6f908e38b9a1db93842b0ca992b · samueleresca/EF.Core.IssueSample](https://github.com/samueleresca/EF.Core.IssueSample/blob/f67e4cae02abc6f908e38b9a1db93842b0ca992b/Catalog/tests/VinylStore.Catalog.Infrastructure.Tests/ItemRepositoryTests.cs)
* [Testing with InMemory - EF Core | Microsoft Docs](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory)
* [Abhiroyq1/eBooks-PDFs-necessary-for-data-analysis-by-Python-R-: Repository for all eBooks/PDFs for data science in Python/R](https://github.com/Abhiroyq1/eBooks-PDFs-necessary-for-data-analysis-by-Python-R-)
* [PacktPublishing/Hands-On-RESTful-Web-Services-with-ASP.NET-Core: Hands-On RESTful Web Services with ASP.NET Core, published by Packt](https://github.com/PacktPublishing/Hands-On-RESTful-Web-Services-with-ASP.NET-Core)
* [ebooks_cheatsheets/Software Development/CQRS at master · amanver16/ebooks_cheatsheets](https://github.com/amanver16/ebooks_cheatsheets/tree/master/Software%20Development/CQRS)
* [iarroyof/nlp-pipeline: Script series for NLP: PMI, TF-IDF and Neural cooccurrence vectorization, vector (TF/IDF & PMI) data base distributed querying and population with Hadoop. Deep learning and kernel learning in sklearn.](https://github.com/iarroyof/nlp-pipeline)
* [Freedesk - Höj och sänkbart skrivbord Från 1349 kr](http://www.thefreedesk.se/)
* [Text faces | Lenny face ( ͡° ͜ʖ ͡°), shrug face ¯\_(ツ)_/¯, look of disapproval ಠ_ಠ and more.](https://textfac.es/)
* [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition: FizzBuzz Enterprise Edition is a no-nonsense implementation of FizzBuzz made by serious businessmen for serious business purposes.](https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition)
* [Slå på och stänga av tv:n med Google Home - Google Nest Hjälp](https://support.google.com/googlenest/answer/7498991?hl=sv&authuser=0)
* [How to do a code review | eng-practices](https://google.github.io/eng-practices/review/reviewer/)
* [(20) Cesium (@CesiumJS) / Twitter](https://twitter.com/CesiumJS?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor)
* [Amelia Wattenberger](https://wattenberger.com/blog/d3)

* [How to build your own Neural Network from scratch in Python](https://towardsdatascience.com/how-to-build-your-own-neural-network-from-scratch-in-python-68998a08e4f6)
* [Heydon/bruck: A prototyping system built with web components and the Houdini Paint API](https://github.com/Heydon/bruck)
* [What Every C#/.Net Developer Needs to Know in 2019 - DZone Web Dev](https://dzone.com/articles/what-every-cnet-developer-need-to-know-in-2019)

