* [Research Data MANTRA](https://mantra.edina.ac.uk/)
* [psf/black: The uncompromising Python code formatter](https://github.com/psf/black)
* [google/yapf: A formatter for Python files](https://github.com/google/yapf#knobs)
* [FastText sentiment analysis for tweets: A straightforward guide](https://towardsdatascience.com/fasttext-sentiment-analysis-for-tweets-a-straightforward-guide-9a8c070449a2)
* [👨‍💻🤖 The 3 best auto formatters for Python - DEV Community 👩‍💻👨‍💻](https://dev.to/igeligel/the-3-best-auto-formatters-for-python-432p)
* [Interactive GIS in Jupyter with ipyleaflet - Jupyter Blog](https://blog.jupyter.org/interactive-gis-in-jupyter-with-ipyleaflet-52f9657fa7a)
* [Rosa Bonheur - Wikipedia](https://en.wikipedia.org/wiki/Rosa_Bonheur#/media/File:Rosa_Bonheur_-_Ploughing_in_Nevers_-_Google_Art_Project.jpg)
* [Happy Brothers - Wikipedia](https://en.wikipedia.org/wiki/Happy_Brothers#/media/File:Merry_brothers_1887.jpg)
* [Are These The 43 Funniest GIFs Of All Time?](https://www.buzzfeed.com/richardhjames/are-these-the-funniest-gifs-of-all-time)
* [Nix manual](https://nixos.org/nix/manual/#chap-introduction)
* [ward clustering python - Sök på Google](https://www.google.com/search?q=ward%20clustering%20python&ie=utf-8&oe=utf-8&aq=t&authuser=0)
* [Hierarchical Clustering with Python and Scikit-Learn](https://stackabuse.com/hierarchical-clustering-with-python-and-scikit-learn/)
* [DARE - Delivering Agile Research Excellence on European e-Infrastructures](http://project-dare.eu/)
* [33+26 most popular GitHub JS repositories in August and September 2019](https://itnext.io/33-26-most-popular-github-js-repositories-in-august-and-september-2019-e8f17da6af4)
* [PowerPoint Presentation](http://project-dare.eu/wp-content/uploads/2018/02/DARE_presentation_EUDAT_Semantic-Services_EOSC_23.1.2018.pdf)
* [Chocolatey Software | Chocolatey - The package manager for Windows](https://chocolatey.org/)
* [TWC9: .NET Conf, .NET Core 3.0 RC1, Cascadia Code Font, Sega Genesis Mini and more | This Week On Channel 9 | Channel 9](https://channel9.msdn.com/Shows/This+Week+On+Channel+9/TWC9-NET-Conf-NET-Core-30-RC1-Cascadia-Code-Font-Sega-Genesis-Mini-and-more)

* [Making Your Code Citable · GitHub Guides](https://guides.github.com/activities/citable-code/)
* [rezakj/scSeqR: scSeqR (Single Cell Sequencing R package) is an interactive R package to works with high-throughput single cell sequencing technologies (i.e scRNA-seq, scVDJ-seq and CITE-seq). As some research studies require a more attuned forms of normalization or spike-in normalization in some cases, scSeqR allows the users to chose from multiple normalization methods and correcting for dropouts (nonzero events counted as zero). Because some of the cell types are more challenging to work with, scSeqR also allows the users to choose from different clustering algorithms (i.e. ward.D, kmeans, ward.D2, hierarchical, etc.) and indexing methods (i.e. silhouette, ccc, kl, gap-stats, etc.) to adjust for sensitivity and stringency in order to find less or more subpopulations of cell types to design both unsupervised and supervised models to best suit your research. scSeqR provides 2D and 3D interactive visualizations, differential expression analysis, filters based on cells and genes, cell helth and cell cycle, merging, normalizing for dropouts and batch differences, pathway analysis, cell type prediction and tools to find marker genes for clusters and conditions. scSeqR inputs single cell data in 10X format, large numeric matrix files and data frames.](https://github.com/rezakj/scSeqR)
* [TOP IDE index](https://pypl.github.io/IDE.html)
* [ahejlsberg (Anders Hejlsberg)](https://github.com/ahejlsberg)
* [Home | King's Digital Lab](https://www.kdl.kcl.ac.uk/)
* [jellyfish · PyPI](https://pypi.org/project/jellyfish/)
* [myCompiler - Run your favourite programming languages online | Product Hunt](https://www.producthunt.com/posts/mycompiler)
* [Shell folder shortcuts - Windows CMD - SS64.com](https://ss64.com/nt/shell.html)
* [Axios](https://www.axios.com/)
* [Top 5 Frameworks / React UI Component Libraries for 2019](https://devias.io/blog/top-5-react-ui-component-libraries-frameworks)
* [The Greatest Ever Infographic - Numberphile - YouTube](https://www.youtube.com/watch?v=3T7jMcstxY0)
* [Mapping JSON to objects using Automapper | Coding Canvas](https://codingcanvas.com/mapping-json-to-objects-using-automapper/)
* [Shared Context between Tests > xUnit.net](https://xunit.net/docs/shared-context.html)
* [Reimagining Plutarch with NLP: Part 2 - Towards Data Science](https://towardsdatascience.com/reimagining-plutarch-with-nlp-part-2-dc4e360baa68)
* [Best Python practices for Data Scientists - Towards Data Science](https://towardsdatascience.com/best-python-practices-for-data-scientists-11056edda8c7)
* [Blog | Precision Movement](https://www.precisionmovement.coach/blog/)
* [Serializing Entity Framework objects to JSON in ASP.NET Web API | StrathWeb. A free flowing web tech monologue.](https://www.strathweb.com/2012/03/serializing-entity-framework-objects-to-json-in-asp-net-web-api/)
* [Quotium | 9 Principles (building blocks) of DSDM – AGILE](http://www.quotium.com/performance/9-principles-building-blocks-dsdm-agile/)
* [BlueStacks - Not Another Android Emulator - 6x Faster Than Any Phone](https://www.bluestacks.com/)
* [Van_Eyck_-_Arnolfini_Portrait.jpg (3087×4226)](https://upload.wikimedia.org/wikipedia/commons/3/33/Van_Eyck_-_Arnolfini_Portrait.jpg)

* [Vagrant by HashiCorp](https://www.vagrantup.com/)
* [Gensim Topic Modeling - A Guide to Building Best LDA models](https://www.machinelearningplus.com/nlp/topic-modeling-gensim-python/)
* [» The Details: Training and Validating Big Models on Big Data Journal of Digital Humanities](http://journalofdigitalhumanities.org/2-1/the-details-by-david-mimno/)
* [Ant Design of React - Ant Design](https://ant.design/docs/react/introduce?ref=devias-io)
* [Dynamic systems development method - Wikipedia](https://en.wikipedia.org/wiki/Dynamic_systems_development_method)
* [Material-UI: A popular React UI framework](https://material-ui.com/)
* [Designers · Evergreen](https://evergreen.segment.com/for-designers/)
* [mobxjs/mobx: Simple, scalable state management.](https://github.com/mobxjs/mobx)
* [.net - Using Automapper to Copy Properties from a Dynamic - Stack Overflow](https://stackoverflow.com/questions/38394587/using-automapper-to-copy-properties-from-a-dynamic)
* [filipw/dotnet-script: Run C# scripts from the .NET CLI.](https://github.com/filipw/dotnet-script)
* [How To Run Voice Activated Google Assistant on Windows PC - TechieLeaf](http://www.techieleaf.net/how-to-run-voice-activated-google-assistant-on-windows-pc/)
* [StrathWeb. A free flowing web tech monologue.](https://www.strathweb.com/)
* [EF.Core.IssueSample/ItemRepositoryTests.cs at f67e4cae02abc6f908e38b9a1db93842b0ca992b · samueleresca/EF.Core.IssueSample](https://github.com/samueleresca/EF.Core.IssueSample/blob/f67e4cae02abc6f908e38b9a1db93842b0ca992b/Catalog/tests/VinylStore.Catalog.Infrastructure.Tests/ItemRepositoryTests.cs)
* [Testing with InMemory - EF Core | Microsoft Docs](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory)
* [Abhiroyq1/eBooks-PDFs-necessary-for-data-analysis-by-Python-R-: Repository for all eBooks/PDFs for data science in Python/R](https://github.com/Abhiroyq1/eBooks-PDFs-necessary-for-data-analysis-by-Python-R-)
* [PacktPublishing/Hands-On-RESTful-Web-Services-with-ASP.NET-Core: Hands-On RESTful Web Services with ASP.NET Core, published by Packt](https://github.com/PacktPublishing/Hands-On-RESTful-Web-Services-with-ASP.NET-Core)
* [ebooks_cheatsheets/Software Development/CQRS at master · amanver16/ebooks_cheatsheets](https://github.com/amanver16/ebooks_cheatsheets/tree/master/Software%20Development/CQRS)
* [iarroyof/nlp-pipeline: Script series for NLP: PMI, TF-IDF and Neural cooccurrence vectorization, vector (TF/IDF & PMI) data base distributed querying and population with Hadoop. Deep learning and kernel learning in sklearn.](https://github.com/iarroyof/nlp-pipeline)
* [Freedesk - Höj och sänkbart skrivbord Från 1349 kr](http://www.thefreedesk.se/)
* [Text faces | Lenny face ( ͡° ͜ʖ ͡°), shrug face ¯\_(ツ)_/¯, look of disapproval ಠ_ಠ and more.](https://textfac.es/)
* [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition: FizzBuzz Enterprise Edition is a no-nonsense implementation of FizzBuzz made by serious businessmen for serious business purposes.](https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition)
* [Slå på och stänga av tv:n med Google Home - Google Nest Hjälp](https://support.google.com/googlenest/answer/7498991?hl=sv&authuser=0)
* [How to do a code review | eng-practices](https://google.github.io/eng-practices/review/reviewer/)
* [(20) Cesium (@CesiumJS) / Twitter](https://twitter.com/CesiumJS?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor)
* [Amelia Wattenberger](https://wattenberger.com/blog/d3)

* [How to build your own Neural Network from scratch in Python](https://towardsdatascience.com/how-to-build-your-own-neural-network-from-scratch-in-python-68998a08e4f6)
* [Heydon/bruck: A prototyping system built with web components and the Houdini Paint API](https://github.com/Heydon/bruck)
* [What Every C#/.Net Developer Needs to Know in 2019 - DZone Web Dev](https://dzone.com/articles/what-every-cnet-developer-need-to-know-in-2019)

* [.NET Application Architecture - Reference Apps](https://github.com/dotnet-architecture)
* [10 Top Javascript Libraries and Tools for an Awesome UI/UX](https://blog.bitsrc.io/10-top-javascript-libraries-and-tools-for-an-awesome-ui-ux-828a314752cc)
* [20 best alternatives to Google Keep as of 2020 - Slant](https://www.slant.co/options/2120/alternatives/~google-keep-alternatives)
* [461 Software Cheat Sheets - Cheatography.com: Cheat Sheets For Every Occasion](https://cheatography.com/software/)
* [A successful Git branching model » nvie.com](https://nvie.com/posts/a-successful-git-branching-model/)
* [algolia/youtube-captions-scraper: Fetch youtube user submitted or fallback to auto-generated captions](https://github.com/algolia/youtube-captions-scraper)
* [ASP.NET Core 3.1 Clean Architecture – Invoice Management App (Part 3 MediatR and FluentValidation) – alexcodetuts](https://alexcodetuts.com/2020/02/09/asp-net-core-3-1-clean-architecture-invoice-management-app-part-3-mediatr-and-fluentvalidation/?fbclid=IwAR37MEs4P7taWAK2i_TH7DF9pvO8IEcWFhUfayqtTL8Y0gb1LtFdgPASbhQ)
* [Åtgärda Windows Update-fel med hjälp av DISM eller kontrollverktyget för systemuppdateringar](https://support.microsoft.com/sv-se/help/947821/fix-windows-update-errors-by-using-the-dism-or-system-update-readiness)
* [beautiful_javascript_charts](http://markibrahim.me/musings/notebooks/beautiful_javascript_charts.html)
* [Binder](https://mybinder.org/)
* [Bluetooth 4.0 USB-adapter | TRUST](https://www.jula.se/catalog/hem-och-hushall/hemelektronik/datortillbehor/usb-kablar-och-adaptrar/bluetooth-4-0-usb-adapter-934704/)
* [Bra mat vid kris](https://www.livsmedelsverket.se/livsmedel-och-innehall/livsmedel-vid-kris/matforrad)
* [‎Casefile True Crime on Apple Podcasts](https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?mt=2&app=podcast)
* [Cheat Sheets for AI, Neural Networks, Machine Learning, Deep Learning & Big Data • CODESIGN.BLOG](https://codesign.blog/2018/08/07/cheat-sheets-for-ai-neural-networks-machine-learning-deep-learning-big-data/)
* [citerus/bookstore-cqrs-example: A showcase for a simple CQRS application](https://github.com/citerus/bookstore-cqrs-example)
* [Clever Chimp - YouTube](https://www.youtube.com/watch?v=gWBw5LetplE)
* [CNN "Exposed" In Controversial Secret Video and Anita Sarkeesian's "Punishment"... - YouTube](https://www.youtube.com/watch?v=Nxb2s2Mv6Pw)
* [Computer Tips & Tricks Everyone Should Know - TechSpot](https://www.techspot.com/guides/676-best-computer-tricks/)
* [Coronavirus COVID-19 (2019-nCoV)](https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6)
* [Crimetown - Wikipedia](https://en.wikipedia.org/wiki/Crimetown)
* [Crono - Notifications, Messages, Clipboard on PC – Appar på Google Play](https://play.google.com/store/apps/details?id=com.getcrono)
* [Cytoscape.js](https://js.cytoscape.org/)
* [data-science-ipython-notebooks/ at master · donnemartin/data-science-ipython-notebooks](https://github.com/donnemartin/data-science-ipython-notebooks?files=1)
* [DatabaseFacade Class (Microsoft.EntityFrameworkCore.Infrastructure) | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.databasefacade?view=efcore-2.1)
* [defeo/jupyterhub-docker: A configuration for a JupyterHub+DockerSpawner+CASAuthenticator server with Traefik proxy, based on docker-compose](https://github.com/defeo/jupyterhub-docker)
* [Dies irae - Wikipedia](https://en.wikipedia.org/wiki/Dies_irae)
* [docker-science/cookiecutter-docker-science: Cookiecutter template for data scientists working with Docker containers](https://github.com/docker-science/cookiecutter-docker-science)
* [dockerspawner/examples/oauth at master · jupyterhub/dockerspawner](https://github.com/jupyterhub/dockerspawner/tree/master/examples/oauth)
* [dodyg/practical-aspnetcore: Practical samples of aspnet core 2.1, 2.2, 3.0 and 3.1 projects you can use. Readme contains explanations on all projects.](https://github.com/dodyg/practical-aspnetcore)
* [doit - Automation tool](https://pydoit.org/)
* [Domkraft | 130 mm ingångshöjd | BAHCO | Jula](https://www.jula.se/catalog/bil-och-garage/garage/lyftdon/domkrafter/domkraft-005933/)
* [Flutter - Beautiful native apps in record time](https://flutter.dev/)
* [Flutter Awesome](https://flutterawesome.com/)
* [Freya Holmér (@FreyaHolmer) / Twitter](https://twitter.com/FreyaHolmer)
* [Gigantum - Build it. Move it. Share it.](https://gigantum.com/)
* [Google Home Commands Cheat Sheet by neckwrestler - Download free from Cheatography - Cheatography.com: Cheat Sheets For Every Occasion](https://cheatography.com/neckwrestler/cheat-sheets/google-home-commands/)
* [Google opens one of the world’s most significant cave painting ‘exhibitions’ in AR and VR – BGR](https://bgr.com/2020/02/27/google-arts-culture-chauvet-cave-exploration-available-in-ar-and-vr/)
* [google/charts](https://github.com/google/charts)
* [Gorilla Sports | Hantlar GS Gummi - 2x15kg från 1249:- hos Gorilla Sports](https://www.gorillasports.se/hantlar-gs-gummi-2x15kg/p/616)
* [Hantelset | Plastklädda betongvikter | KAYOBA | Jula](https://www.jula.se/catalog/fritid/traning-och-halsa/traningsredskap/hantlar-och-skivstanger/hantelset-951150/#tab04)
* [Hantlar RubberDumbbells 2 x 12,5 kg - Fri frakt och 30 dagars öppet köp.](https://www.sporttema.se/styrketraening/hantlar/hantlar-rubberdumbbells-2-x-125-kg)
* [High CPU usage by ACPI.sys ("system" process) - Sök på Google](https://www.google.com/search?q=High+CPU+usage+by+ACPI.sys+(%22system%22+process)&ie=utf-8&oe=utf-8&aq=t&authuser=0)
* [Histogram  |  Charts  |  Google Developers](https://developers.google.com/chart/interactive/docs/gallery/histogram?authuser=0)
* [Home · Cookiecutter Docker Science](https://docker-science.github.io/)
* [How to Make YouTube Kids Safer for Your Kids | WIRED](https://www.wired.com/story/youtube-kids-parental-settings-safer/)
* [HP Spectre x360 Convertable 13 display issues and cpu usage ... - HP Support Community - 7102935](https://h30434.www3.hp.com/t5/Notebook-Video-Display-and-Touch/HP-Spectre-x360-Convertable-13-display-issues-and-cpu-usage/td-p/7102935)
* [Hp x360 power on but no picture or backlight - 0.7V on the ram memory - YouTube](https://www.youtube.com/watch?v=lU1fReBwhKo)
* [Introduction to R Online Course | DataCamp](https://www.datacamp.com/courses/free-introduction-to-r)
* [jakevdp/PythonDataScienceHandbook: Python Data Science Handbook: full text in Jupyter Notebooks](https://github.com/jakevdp/PythonDataScienceHandbook)
* [jupyterlab/jupyterlab-git: A Git extension for JupyterLab](https://github.com/jupyterlab/jupyterlab-git)
* [krassowski/jupyterlab-lsp: Language Server Protocol integration for JupyterLab (code navigation + hover suggestions + linters + autocompletion + rename)](https://github.com/krassowski/jupyterlab-lsp)
* [List of Nestlé brands - Wikipedia](https://en.wikipedia.org/wiki/List_of_Nestl%C3%A9_brands)
* [Microsoft Data Analysis: .NET for Jupyter Notebooks, DataFrame for .NET -- Visual Studio Magazine](https://visualstudiomagazine.com/articles/2019/12/16/jupyter-net.aspx)
* [Microsoft Updates Jupyter Notebook Preview for .NET Core -- Visual Studio Magazine](https://visualstudiomagazine.com/articles/2020/02/06/net-jupyter-preview-2.aspx)
* [mpld3 — Bringing Matplotlib to the Browser](http://mpld3.github.io/)
* [Nestlé – Wikipedia](https://sv.wikipedia.org/wiki/Nestl%C3%A9#N%C3%A5gra_varum%C3%A4rken)
* [nteract: write your next code-driven story.](https://nteract.io/)
* [nteract/papermill: 📚 Parameterize, execute, and analyze notebooks](https://github.com/nteract/papermill)
* [O'Reilly Graph Algorithms Book - Neo4j Graph Database Platform](https://neo4j.com/lp/book-graph-algorithms-fb-eu/?utm_source=Facebook&utm_medium=Paid+Social&utm_campaign=EU+-+Prospecting+ENT&utm_adgroup=FB:EU+-+Prospecting+ENT+Leads+LAL+-+Graph+Algorithms&fbclid=IwAR0NfWjYXZHp_mcWLT86-TzcGWDfXc55QYKLZgq3PyrHsEYVnlpQbJLzZYI)
* [Ont i ljumsken vid löpning](https://www.linabjorkskog.com/traning/ont-i-ljumsken-vid-lopning)
* [Page Not Found](https://www.amazon.com/Wireless-Transmitter-SmartSee-M100-Streaming/dp/B07KB15C7N)
* [Pexpect version 4.8 — Pexpect 4.8 documentation](https://pexpect.readthedocs.io/en/stable/)
* [Pro touch Rylungo II UX funktionströja - PETROL BLUE MELANGE - Köp online hos Intersport](https://www.intersport.se/klader/trojor/traningstrojor/pro-touch-rylungo-ii-ux-funktionstroja-herr/petrol-blue-melange)
* [Pulverbrandsläckare | Påfyllningsbar | OSEC | Jula](https://www.jula.se/catalog/hem-och-hushall/brand-och-sakerhet/brand/brandslackare/pulverbrandslackare-442046/#tab04)
* [python - combining multiple columns pandas groupby - Stack Overflow](https://stackoverflow.com/questions/48551297/combining-multiple-columns-pandas-groupby)
* [quantopian/qgrid: An interactive grid for sorting, filtering, and editing DataFrames in Jupyter notebooks](https://github.com/quantopian/qgrid)
* [R for Data Science](https://r4ds.had.co.nz/)
* [R-bloggers | R news and tutorials contributed by hundreds of R bloggers](https://www.r-bloggers.com/)
* [RichardLitt/awesome-fantasy: Fantasy literature worth reading](https://github.com/RichardLitt/awesome-fantasy)
* [Robot Fail Compilation - YouTube](https://www.youtube.com/watch?v=1Xruds0J86I)
* [Static Site Generator | Nikola](https://getnikola.com/)
* [Tesseract.js | Pure Javascript OCR for 100 Languages!](https://tesseract.projectnaptha.com/)
* [tfidf nrmalize - Sök på Google](https://www.google.com/search?q=tfidf+nrmalize&ie=utf-8&oe=utf-8&aq=t&authuser=0)
* [The 100 Best Podcasts to Listen to Right Now (2020)](https://www.samuelthomasdavies.com/best-podcasts/)
* [The A.V. Club | Pop culture obsessives writing for the pop culture obsessed.](https://www.avclub.com/)
* [The Google Home Commands Cheat Sheet](https://www.makeuseof.com/tag/google-home-commands-cheat-sheet/)
* [Tickets for DevSum 2020 - DevSum](https://www.devsum.se/tickets)
* [Top 10 VS Code Extensions for Software Developers - Level Up Coding](https://levelup.gitconnected.com/top-10-vs-code-extensions-for-software-developers-9c3a807c6656)
* [Top 10 Wireless Display Adapters of 2019 | Video Review](https://wiki.ezvid.com/best-wireless-display-adapters)
* [tryck_matforradslista-2019.pdf](https://www.livsmedelsverket.se/globalassets/publikationsdatabas/folder/tryck_matforradslista-2019.pdf?AspxAutoDetectCookieSupport=1)
* [Usage - db-migrate](https://db-migrate.readthedocs.io/en/latest/Getting%20Started/usage/)
* [Using MALLET LDA to Learn Why Players Hate Pokémon Sword /Shield](https://towardsdatascience.com/using-mallet-lda-to-learn-why-players-hate-pok%C3%A9mon-sword-shield-23b12e4fc395)
* [Vad-bör-du-ha-i-din-krislåda.pdf](https://www.civil.se/wp-content/blogs.dir/1/files/2017/04/Vad-b%c3%b6r-du-ha-i-din-krisl%c3%a5da.pdf)
* [vidaXL Dumbbell Set 30kg - Hitta bästa pris på Prisjakt](https://www.prisjakt.nu/produkt.php?p=3120382)
* [voila-dashboards/voila: Voilà turns Jupyter notebooks into standalone web applications](https://github.com/voila-dashboards/voila)
* [Vue CLI 3: A Game Changer for Frontend Development - DZone Web Dev](https://dzone.com/articles/vue-cli-3-a-game-changer-for-frontend-development)
* [What `R` you? (R list in python) | R-bloggers](https://www.r-bloggers.com/what-r-you-r-list-in-python/)
* [What does Judaism say about Christmas: A night we don't study, a day soaked in sorrows, and today's materialism HQ in progress](https://www.sefaria.org/sheets/51928.2?lang=bi)
* [Why this creepy melody is in so many movies - YouTube](https://www.youtube.com/watch?v=-3-bVRYRnSM)
* [Xamarin | Open-source mobile app platform for .NET](https://dotnet.microsoft.com/apps/xamarin)
