
* [.NET Application Architecture - Reference Apps](https://github.com/dotnet-architecture)
* [.net - Using Automapper to Copy Properties from a Dynamic - Stack Overflow](https://stackoverflow.com/questions/38394587/using-automapper-to-copy-properties-from-a-dynamic)
* [.NET Core with Jupyter Notebooks - Available today | Preview 1 | .NET Blog](https://devblogs.microsoft.com/dotnet/net-core-with-juypter-notebooks-is-here-preview-1/)
* [.NET documentation | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/)
* [ASP.NET Boilerplate](https://github.com/aspnetboilerplate)
* [ASP.NET Core 3.1 Clean Architecture – Invoice Management App (Part 3 MediatR and FluentValidation) – alexcodetuts](https://alexcodetuts.com/2020/02/09/asp-net-core-3-1-clean-architecture-invoice-management-app-part-3-mediatr-and-fluentvalidation/?fbclid=IwAR37MEs4P7taWAK2i_TH7DF9pvO8IEcWFhUfayqtTL8Y0gb1LtFdgPASbhQ)
* [abpframework/abp: Open Source Web Application Framework for ASP.NET Core](https://github.com/abpframework/abp)
* [Adventures in .NET](https://devchat.tv/adventures-in-dotnet/)
* [ahejlsberg (Anders Hejlsberg)](https://github.com/ahejlsberg)
* [citerus/bookstore-cqrs-example: A showcase for a simple CQRS application](https://github.com/citerus/bookstore-cqrs-example)

* [Agile Modeling (AM) Home Page: Effective Practices for Modeling and Documentation](http://agilemodeling.com/)

* [Best Python practices for Data Scientists - Towards Data Science](https://towardsdatascience.com/best-python-practices-for-data-scientists-11056edda8c7)
* [» The Details: Training and Validating Big Models on Big Data Journal of Digital Humanities](http://journalofdigitalhumanities.org/2-1/the-details-by-david-mimno/)
* [Abhiroyq1/eBooks-PDFs-necessary-for-data-analysis-by-Python-R-: Repository for all eBooks/PDFs for data science in Python/R](https://github.com/Abhiroyq1/eBooks-PDFs-necessary-for-data-analysis-by-Python-R-)
* [Binder](https://mybinder.org/)
* [AI |](https://www.ai.se/en)
* [Cheat Sheets for AI, Neural Networks, Machine Learning, Deep Learning & Big Data • CODESIGN.BLOG](https://codesign.blog/2018/08/07/cheat-sheets-for-ai-neural-networks-machine-learning-deep-learning-big-data/)

* [👨‍💻🤖 The 3 best auto formatters for Python - DEV Community 👩‍💻👨‍💻](https://dev.to/igeligel/the-3-best-auto-formatters-for-python-432p)
* [algolia/youtube-captions-scraper: Fetch youtube user submitted or fallback to auto-generated captions](https://github.com/algolia/youtube-captions-scraper)

* [(1) What are the main differences between the word embeddings of ELMo, BERT, Word2vec, and GloVe? - Quora](https://www.quora.com/What-are-the-main-differences-between-the-word-embeddings-of-ELMo-BERT-Word2vec-and-GloVe)
* [CLT toolkit | Centre for Language Technology, Gothenburg](http://www.clt.gu.se/clt-toolkit)
* [AllenNLP](https://allennlp.org/)

* [(20) Cesium (@CesiumJS) / Twitter](https://twitter.com/CesiumJS?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor)
* [11 React Boilerplates and Starter Kits for 2019 - Bits and Pieces](https://blog.bitsrc.io/11-react-application-boilerplates-for-2019-b49a8226ea54)
* [10 Top Javascript Libraries and Tools for an Awesome UI/UX](https://blog.bitsrc.io/10-top-javascript-libraries-and-tools-for-an-awesome-ui-ux-828a314752cc)
* [27 Best JavaScript drawing libraries as of 2019 - Slant](https://www.slant.co/topics/28/~best-javascript-drawing-libraries)
* [All the fundamental React.js concepts, jammed into this one article](https://www.freecodecamp.org/news/all-the-fundamental-react-js-concepts-jammed-into-this-single-medium-article-c83f9b53eac2/)
* [Ant Design of React - Ant Design](https://ant.design/docs/react/introduce?ref=devias-io)
* [beautiful_javascript_charts](http://markibrahim.me/musings/notebooks/beautiful_javascript_charts.html)

* [25 Best Podcasts of 2019 - Top Podcasts to Listen to Now](https://www.goodhousekeeping.com/life/entertainment/g28353940/best-podcasts/?slide=3)
* [461 Software Cheat Sheets - Cheatography.com: Cheat Sheets For Every Occasion](https://cheatography.com/software/)
* [5 Books To Improve Your Fast & Slow Thinking - Towards Data Science](https://towardsdatascience.com/5-books-to-improve-your-fast-slow-thinking-96cfb798ecbc)
* [A successful Git branching model » nvie.com](https://nvie.com/posts/a-successful-git-branching-model/)
* [Are These The 43 Funniest GIFs Of All Time?](https://www.buzzfeed.com/richardhjames/are-these-the-funniest-gifs-of-all-time)
* [Astronomy Picture of the Day](https://apod.nasa.gov/apod/astropix.html)
* [Amelia Wattenberger](https://wattenberger.com/blog/d3)
* [Blog | Precision Movement](https://www.precisionmovement.coach/blog/)
* [Can't connect through jumpbox · Issue #18 · microsoft/vscode-remote-release](https://github.com/microsoft/vscode-remote-release/issues/18)
* [‎Casefile True Crime on Apple Podcasts](https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?mt=2&app=podcast)
* [Bra mat vid kris](https://www.livsmedelsverket.se/livsmedel-och-innehall/livsmedel-vid-kris/matforrad)
* [Chaos Seeds Series by Aleron Kong](https://www.goodreads.com/series/179187-chaos-seeds)
* [Chocolatey Software | Chocolatey - The package manager for Windows](https://chocolatey.org/)
* [CNN "Exposed" In Controversial Secret Video and Anita Sarkeesian's "Punishment"... - YouTube](https://www.youtube.com/watch?v=Nxb2s2Mv6Pw)
* [Clever Chimp - YouTube](https://www.youtube.com/watch?v=gWBw5LetplE)


* [Axios](https://www.axios.com/)
* [Crono - Notifications, Messages, Clipboard on PC – Appar på Google Play](https://play.google.com/store/apps/details?id=com.getcrono)
* [Cytoscape.js](https://js.cytoscape.org/)
* [danielgerlag/workflow-core: Lightweight workflow engine for .NET Standard](https://github.com/danielgerlag/workflow-core)
* [DanielRosenwasser (Daniel Rosenwasser)](https://github.com/DanielRosenwasser)
* [DARE - Delivering Agile Research Excellence on European e-Infrastructures](http://project-dare.eu/)
* [Darknet Diaries – True stories from the dark side of the Internet.](https://darknetdiaries.com/)
* [Data Management - Procedures | Policies and procedures | University of the Sunshine Coast](https://www.usc.edu.au/explore/policies-and-procedures/data-management-procedures)
* [Data management checklist | Fairdata](https://www.fairdata.fi/en/why-fairdata/data-management-checklist/)
* [data-science-ipython-notebooks/ at master · donnemartin/data-science-ipython-notebooks](https://github.com/donnemartin/data-science-ipython-notebooks?files=1)
* [DatabaseFacade Class (Microsoft.EntityFrameworkCore.Infrastructure) | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.databasefacade?view=efcore-2.1)
* [defeo/jupyterhub-docker: A configuration for a JupyterHub+DockerSpawner+CASAuthenticator server with Traefik proxy, based on docker-compose](https://github.com/defeo/jupyterhub-docker)
* [Designers · Evergreen](https://evergreen.segment.com/for-designers/)
* [Dies irae - Wikipedia](https://en.wikipedia.org/wiki/Dies_irae)
* [Digitala infrastrukturer – översikt – Digisam](http://www.digisam.se/digitala-infrastrukturer-oversikt/)
* [MAUS](https://hub.docker.com/r/stevecassidy/maus/)
* [docker-science/cookiecutter-docker-science: Cookiecutter template for data scientists working with Docker containers](https://github.com/docker-science/cookiecutter-docker-science)
* [dockerspawner/examples/oauth at master · jupyterhub/dockerspawner](https://github.com/jupyterhub/dockerspawner/tree/master/examples/oauth)
* [dodyg/practical-aspnetcore: Practical samples of aspnet core 2.1, 2.2, 3.0 and 3.1 projects you can use. Readme contains explanations on all projects.](https://github.com/dodyg/practical-aspnetcore)
* [doit - Automation tool](https://pydoit.org/)
* [Domkraft | 130 mm ingångshöjd | BAHCO | Jula](https://www.jula.se/catalog/bil-och-garage/garage/lyftdon/domkrafter/domkraft-005933/)
* [Dynamic systems development method - Wikipedia](https://en.wikipedia.org/wiki/Dynamic_systems_development_method)
* [ebooks_cheatsheets/Software Development/CQRS at master · amanver16/ebooks_cheatsheets](https://github.com/amanver16/ebooks_cheatsheets/tree/master/Software%20Development/CQRS)
* [EF.Core.IssueSample/ItemRepositoryTests.cs at f67e4cae02abc6f908e38b9a1db93842b0ca992b · samueleresca/EF.Core.IssueSample](https://github.com/samueleresca/EF.Core.IssueSample/blob/f67e4cae02abc6f908e38b9a1db93842b0ca992b/Catalog/tests/VinylStore.Catalog.Infrastructure.Tests/ItemRepositoryTests.cs)
* [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition: FizzBuzz Enterprise Edition is a no-nonsense implementation of FizzBuzz made by serious businessmen for serious business purposes.](https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition)
* [erikmansson/pair-sonos](https://github.com/erikmansson/pair-sonos)
* [Explore thousands of open source components to build your apps · Bit](https://bit.dev/explore)
* [facebook/create-react-app: Set up a modern web app by running one command.](https://github.com/facebook/create-react-app)
* [Faceted Search | Synthesis Lectures on Information Concepts, Retrieval, and Services](https://www.morganclaypool.com/doi/abs/10.2200/S00190ED1V01Y200904ICR005)
* [FastText sentiment analysis for tweets: A straightforward guide](https://towardsdatascience.com/fasttext-sentiment-analysis-for-tweets-a-straightforward-guide-9a8c070449a2)
* [filipw/dotnet-script: Run C# scripts from the .NET CLI.](https://github.com/filipw/dotnet-script)
* [Flutter - Beautiful native apps in record time](https://flutter.dev/)
* [Flutter Awesome](https://flutterawesome.com/)
* [Forskarens handbok för öppen forskning – Historia i en digital värld](https://digihist.se/handbok/)
* [Från stocksåg till skördare - YouTube](https://www.youtube.com/watch?v=B2nTlsYl37I)
* [Freedesk - Höj och sänkbart skrivbord Från 1349 kr](http://www.thefreedesk.se/)
* [Freya Holmér (@FreyaHolmer) / Twitter](https://twitter.com/FreyaHolmer)
* [Garmin Vivoactive 4S GPS Wi-Fi WW, smartklocka med GPS - Grå - Pulsklocka | XXL](https://www.xxl.se/garmin-vivoactive-4s-gps-wi-fi-ww-smartklocka-med-gps-gra/p/1169693_1_style)
* [gclient · PyPI](https://pypi.org/project/gclient/)
* [Gensim Topic Modeling - A Guide to Building Best LDA models](https://www.machinelearningplus.com/nlp/topic-modeling-gensim-python/)
* [Gigantum - Build it. Move it. Share it.](https://gigantum.com/)
* [Git LFS | GitLab](https://docs.gitlab.com/ee/administration/lfs/manage_large_binaries_with_git_lfs.html)
* [Google Grupper](https://groups.google.com/forum/#!topic/gensim/yJan7QlKr4I)
* [Google Home Commands Cheat Sheet by neckwrestler - Download free from Cheatography - Cheatography.com: Cheat Sheets For Every Occasion](https://cheatography.com/neckwrestler/cheat-sheets/google-home-commands/)
* [Google opens one of the world’s most significant cave painting ‘exhibitions’ in AR and VR – BGR](https://bgr.com/2020/02/27/google-arts-culture-chauvet-cave-exploration-available-in-ar-and-vr/)
* [google/charts](https://github.com/google/charts)
* [google/yapf: A formatter for Python files](https://github.com/google/yapf#knobs)
* [Gorilla Sports | Hantlar GS Gummi - 2x15kg från 1249:- hos Gorilla Sports](https://www.gorillasports.se/hantlar-gs-gummi-2x15kg/p/616)
* [Griffin iTrip Clip - You can turn voice prompts … - Reddit](https://www.reddit.com/r/headphones/comments/6jsp2w/griffin_itrip_clip_you_can_turn_voice_prompts_off/)
* [gRPC](https://grpc.io/)
* [Hantelset | Plastklädda betongvikter | KAYOBA | Jula](https://www.jula.se/catalog/fritid/traning-och-halsa/traningsredskap/hantlar-och-skivstanger/hantelset-951150/#tab04)
* [Hantlar RubberDumbbells 2 x 12,5 kg - Fri frakt och 30 dagars öppet köp.](https://www.sporttema.se/styrketraening/hantlar/hantlar-rubberdumbbells-2-x-125-kg)
* [Happy Brothers - Wikipedia](https://en.wikipedia.org/wiki/Happy_Brothers#/media/File:Merry_brothers_1887.jpg)
* [help-me-with/gensim.md at master · valentinarho/help-me-with](https://github.com/valentinarho/help-me-with/blob/master/gensim.md)
* [Heydon/bruck: A prototyping system built with web components and the Houdini Paint API](https://github.com/Heydon/bruck)
* [Hierarchical Clustering with Python and Scikit-Learn](https://stackabuse.com/hierarchical-clustering-with-python-and-scikit-learn/)
* [High CPU usage by ACPI.sys ("system" process) - Sök på Google](https://www.google.com/search?q=High+CPU+usage+by+ACPI.sys+(%22system%22+process)&ie=utf-8&oe=utf-8&aq=t&authuser=0)
* [Histogram  |  Charts  |  Google Developers](https://developers.google.com/chart/interactive/docs/gallery/histogram?authuser=0)
* [HNM-PLoP_final](https://hillside.net/plop/2011/papers/E-13-Hoda.pdf)
* [Home - DevOps.com](https://devops.com/)
* [Home · Cookiecutter Docker Science](https://docker-science.github.io/)
* [Home | King's Digital Lab](https://www.kdl.kcl.ac.uk/)
* [How to build your own Neural Network from scratch in Python](https://towardsdatascience.com/how-to-build-your-own-neural-network-from-scratch-in-python-68998a08e4f6)
* [How to do a code review | eng-practices](https://google.github.io/eng-practices/review/reviewer/)
* [How to Make YouTube Kids Safer for Your Kids | WIRED](https://www.wired.com/story/youtube-kids-parental-settings-safer/)
* [How To Run Voice Activated Google Assistant on Windows PC - TechieLeaf](http://www.techieleaf.net/how-to-run-voice-activated-google-assistant-on-windows-pc/)
* [How to Smile Naturally: 13 Steps (with Pictures) - wikiHow](https://www.wikihow.com/Smile-Naturally)
* [How to update the language server to the latest stable version · Issue #3977 · microsoft/vscode-python](https://github.com/microsoft/vscode-python/issues/3977)
* [How to use SSH to proxy through a Linux jump host - TechRepublic](https://www.techrepublic.com/article/how-to-use-ssh-to-proxy-through-a-linux-jump-host/)
* [HP Spectre x360 Convertable 13 display issues and cpu usage ... - HP Support Community - 7102935](https://h30434.www3.hp.com/t5/Notebook-Video-Display-and-Touch/HP-Spectre-x360-Convertable-13-display-issues-and-cpu-usage/td-p/7102935)
* [Hp x360 power on but no picture or backlight - 0.7V on the ram memory - YouTube](https://www.youtube.com/watch?v=lU1fReBwhKo)
* [https://github.com/dotnet-architecture/eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers)
* [https://github.com/google-research/bert](https://github.com/google-research/bert)
* [https://github.com/JasonKessler/scattertext/tree/master/scattertext](https://github.com/JasonKessler/scattertext/tree/master/scattertext)
* [https://github.com/stanfordnlp](https://github.com/stanfordnlp)
* [https://github.com/VowpalWabbit/vowpal_wabbit/wiki](https://github.com/VowpalWabbit/vowpal_wabbit/wiki)
* [https://www.ideals.illinois.edu/bitstream/handle/2142/8267/?sequence=1](https://www.ideals.illinois.edu/bitstream/handle/2142/8267/?sequence=1)
* [iarroyof/nlp-pipeline: Script series for NLP: PMI, TF-IDF and Neural cooccurrence vectorization, vector (TF/IDF & PMI) data base distributed querying and population with Hadoop. Deep learning and kernel learning in sklearn.](https://github.com/iarroyof/nlp-pipeline)
* [IFFIS 2019 – Infra­struk­tur för forsk­nings­in­for­ma­tion 2019, 19 november](https://www.delegia.com/app/netattm/attendee/page/89312)
* [Installation | AdoptOpenJDK - Open source, prebuilt OpenJDK binaries](https://adoptopenjdk.net/installation.html#x64_mac-jre)
* [Installing Music from a Computer on a Garmin Music Watch Using Garmin Express | vívoactive® 4S | Garmin Support](https://support.garmin.com/en-US/?faq=1ZDlVH09XB1169yYD5FIWA&productID=643399&tab=topics&topicTag=region_music)
* [Interactive GIS in Jupyter with ipyleaflet - Jupyter Blog](https://blog.jupyter.org/interactive-gis-in-jupyter-with-ipyleaflet-52f9657fa7a)
* [Introduction - Mithril.js](https://mithril.js.org/)
* [Introduction to R Online Course | DataCamp](https://www.datacamp.com/courses/free-introduction-to-r)
* [jakevdp/PythonDataScienceHandbook: Python Data Science Handbook: full text in Jupyter Notebooks](https://github.com/jakevdp/PythonDataScienceHandbook)
* [Javascript Competency Matrix - Tucker Connelly - Medium](https://medium.com/@TuckerConnelly/javascript-competency-matrix-6831817885d9)
* [jellyfish · PyPI](https://pypi.org/project/jellyfish/)
* [jgraph/mxgraph: mxGraph is a fully client side JavaScript diagramming library](https://github.com/jgraph/mxgraph)
* [jupyterlab/jupyterlab-git: A Git extension for JupyterLab](https://github.com/jupyterlab/jupyterlab-git)
* [krassowski/jupyterlab-lsp: Language Server Protocol integration for JupyterLab (code navigation + hover suggestions + linters + autocompletion + rename)](https://github.com/krassowski/jupyterlab-lsp)
* [Language models for Swedish authorities | AI](https://www.ai.se/en/project/language-models-swedish-authorities)
* [Learning JavaScript Design Patterns](https://addyosmani.com/resources/essentialjsdesignpatterns/book/)
* [Lerna · A tool for managing JavaScript projects with multiple packages.](https://lerna.js.org/)
* [List of Nestlé brands - Wikipedia](https://en.wikipedia.org/wiki/List_of_Nestl%C3%A9_brands)
* [Magnetfiske - Guide till Utrustning - Fynd - Bästa Platsen - Detektorist.se](http://www.detektorist.se/magnetfiske/)
* [Making Your Code Citable · GitHub Guides](https://guides.github.com/activities/citable-code/)
* [Mapping JSON to objects using Automapper | Coding Canvas](https://codingcanvas.com/mapping-json-to-objects-using-automapper/)
* [MapPorn – The Official Blog of /r/MapPorn](http://mapporn.org/)
* [Markdown Preview Mermaid Support - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid)
* [Material-UI: A popular React UI framework](https://material-ui.com/)
* [MESA Mega 160 DIM Ljusterapilampa | E00894](https://www.ergoff.se/produkter/friskvaard/ljusterapi/mesa-mega-160-dim-innolux-ljusterapilampa.html)
* [Microsoft Data Analysis: .NET for Jupyter Notebooks, DataFrame for .NET -- Visual Studio Magazine](https://visualstudiomagazine.com/articles/2019/12/16/jupyter-net.aspx)
* [Microsoft Updates Jupyter Notebook Preview for .NET Core -- Visual Studio Magazine](https://visualstudiomagazine.com/articles/2020/02/06/net-jupyter-preview-2.aspx)
* [Migrate from ASP.NET Core 2.2 to 3.0 | Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio)
* [mobxjs/mobx: Simple, scalable state management.](https://github.com/mobxjs/mobx)
* [mpld3 — Bringing Matplotlib to the Browser](http://mpld3.github.io/)
* [myCompiler - Run your favourite programming languages online | Product Hunt](https://www.producthunt.com/posts/mycompiler)
* [NASA Images | NASA](https://www.nasa.gov/multimedia/imagegallery/index.html)
* [NEALT](http://omilia.uio.no/nealt/)
* [Nestlé – Wikipedia](https://sv.wikipedia.org/wiki/Nestl%C3%A9#N%C3%A5gra_varum%C3%A4rken)
* [NHadi/Dermayon: Dermayon is Library for supporting build large application,distributed application, scalable, microservices, cqrs, event sourcing, including generic ef repository pattern with unit of work, generic mongo repository pattern with unit of work, kafka, etc](https://github.com/NHadi/Dermayon?fbclid=IwAR0ZC0wW6_Ck_4ZBzIkWCkjcWRLmA-zGMj3umTV9zP4OO1BeZN-aBuSUXIs)
* [Nix manual](https://nixos.org/nix/manual/#chap-introduction)
* [NoDaLiDa 2019, Turku, Finland](https://nodalida2019.org/)
* [nodegoat](https://nodegoat.net/)
* [nteract: write your next code-driven story.](https://nteract.io/)
* [nteract/papermill: 📚 Parameterize, execute, and analyze notebooks](https://github.com/nteract/papermill)
* [NuGet Gallery | Pdfium.Net.SDK 4.24.2704](https://www.nuget.org/packages/Pdfium.Net.SDK/)
* [Nybyggarland | Öppet arkiv | oppetarkiv.se](https://www.oppetarkiv.se/etikett/titel/Nybyggarland/)
* [O'Reilly Graph Algorithms Book - Neo4j Graph Database Platform](https://neo4j.com/lp/book-graph-algorithms-fb-eu/?utm_source=Facebook&utm_medium=Paid+Social&utm_campaign=EU+-+Prospecting+ENT&utm_adgroup=FB:EU+-+Prospecting+ENT+Leads+LAL+-+Graph+Algorithms&fbclid=IwAR0NfWjYXZHp_mcWLT86-TzcGWDfXc55QYKLZgq3PyrHsEYVnlpQbJLzZYI)
* [Online FlowChart & Diagrams Editor - Mermaid Live Editor](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ)
* [Ont i ljumsken vid löpning](https://www.linabjorkskog.com/traning/ont-i-ljumsken-vid-lopning)
* [PacktPublishing/Hands-On-RESTful-Web-Services-with-ASP.NET-Core: Hands-On RESTful Web Services with ASP.NET Core, published by Packt](https://github.com/PacktPublishing/Hands-On-RESTful-Web-Services-with-ASP.NET-Core)
* [Page Not Found](https://www.amazon.com/Wireless-Transmitter-SmartSee-M100-Streaming/dp/B07KB15C7N)
* [paulcutting/skills-matrix: React app to track a teams skill levels across and show improvement areas.](https://github.com/paulcutting/skills-matrix)
* [pdfium - Git at Google](https://pdfium.googlesource.com/pdfium/)
* [Perplexity To Evaluate Topic Models](http://qpleple.com/perplexity-to-evaluate-topic-models/)
* [Personalhandbok Information för dig som är anställd vid Skolan för information- och kommunikationsteknik - PDF Gratis nedladdning](https://docplayer.se/3429811-Personalhandbok-information-for-dig-som-ar-anstalld-vid-skolan-for-information-och-kommunikationsteknik.html)
* [Pexpect version 4.8 — Pexpect 4.8 documentation](https://pexpect.readthedocs.io/en/stable/)
* [PII: B9780080448947013336](http://www.ub.edu/gdne/amaydeusp_archivos/encyclopedia_of_education10.pdf)
* [PowerPoint Presentation](http://project-dare.eu/wp-content/uploads/2018/02/DARE_presentation_EUDAT_Semantic-Services_EOSC_23.1.2018.pdf)
* [Pro touch Rylungo II UX funktionströja - PETROL BLUE MELANGE - Köp online hos Intersport](https://www.intersport.se/klader/trojor/traningstrojor/pro-touch-rylungo-ii-ux-funktionstroja-herr/petrol-blue-melange)
* [Programmer Competency Matrix | Sijin Joseph](http://sijinjoseph.com/programmer-competency-matrix/)
* [psf/black: The uncompromising Python code formatter](https://github.com/psf/black)
* [Pulverbrandsläckare | Påfyllningsbar | OSEC | Jula](https://www.jula.se/catalog/hem-och-hushall/brand-och-sakerhet/brand/brandslackare/pulverbrandslackare-442046/#tab04)
* [pymc3 - Sök på Google](https://www.google.com/search?q=pymc3&oq=pymd3&aqs=chrome.1.69i57j0l3.4889j0j4&client=ms-unknown&sourceid=chrome-mobile&ie=UTF-8&authuser=0)
* [PyPy - Welcome to PyPy](https://pypy.org/)
* [python - combining multiple columns pandas groupby - Stack Overflow](https://stackoverflow.com/questions/48551297/combining-multiple-columns-pandas-groupby)
* [Python Assert Statement](https://www.programiz.com/python-programming/assert-statement)
* [quantopian/qgrid: An interactive grid for sorting, filtering, and editing DataFrames in Jupyter notebooks](https://github.com/quantopian/qgrid)
* [Quotium | 9 Principles (building blocks) of DSDM – AGILE](http://www.quotium.com/performance/9-principles-building-blocks-dsdm-agile/)
* [R for Data Science](https://r4ds.had.co.nz/)
* [R-bloggers | R news and tutorials contributed by hundreds of R bloggers](https://www.r-bloggers.com/)
* [r-cheat-sheet.key](https://rstudio.com/wp-content/uploads/2016/05/base-r.pdf)
* [Raise the bar: a beginner's guide to lifting weights | Life and style | The Guardian](https://www.theguardian.com/lifeandstyle/2017/feb/01/weight-training-get-fit-personal-trainer-zanna-van-dijk)
* [Reimagining Plutarch with NLP: Part 2 - Towards Data Science](https://towardsdatascience.com/reimagining-plutarch-with-nlp-part-2-dc4e360baa68)
* [Research Data MANTRA](https://mantra.edina.ac.uk/)
* [rezakj/scSeqR: scSeqR (Single Cell Sequencing R package) is an interactive R package to works with high-throughput single cell sequencing technologies (i.e scRNA-seq, scVDJ-seq and CITE-seq). As some research studies require a more attuned forms of normalization or spike-in normalization in some cases, scSeqR allows the users to chose from multiple normalization methods and correcting for dropouts (nonzero events counted as zero). Because some of the cell types are more challenging to work with, scSeqR also allows the users to choose from different clustering algorithms (i.e. ward.D, kmeans, ward.D2, hierarchical, etc.) and indexing methods (i.e. silhouette, ccc, kl, gap-stats, etc.) to adjust for sensitivity and stringency in order to find less or more subpopulations of cell types to design both unsupervised and supervised models to best suit your research. scSeqR provides 2D and 3D interactive visualizations, differential expression analysis, filters based on cells and genes, cell helth and cell cycle, merging, normalizing for dropouts and batch differences, pathway analysis, cell type prediction and tools to find marker genes for clusters and conditions. scSeqR inputs single cell data in 10X format, large numeric matrix files and data frames.](https://github.com/rezakj/scSeqR)
* [RichardLitt/awesome-fantasy: Fantasy literature worth reading](https://github.com/RichardLitt/awesome-fantasy)
* [Riksbankens Jubileumsfond | Digarv](https://www.rj.se/Forskning_finansiering/digarv/)
* [Robot Fail Compilation - YouTube](https://www.youtube.com/watch?v=1Xruds0J86I)
* [Rosa Bonheur - Wikipedia](https://en.wikipedia.org/wiki/Rosa_Bonheur#/media/File:Rosa_Bonheur_-_Ploughing_in_Nevers_-_Google_Art_Project.jpg)
* [Så ska Sverige ta ledartröjan inom AI | RISE](https://www.ri.se/sv/berattelser/sa-ska-sverige-ta-ledartrojan-inom-ai)
* [Sankey Diagram | AnyChart Gallery | AnyChart](https://www.anychart.com/products/anychart/gallery/Sankey_Diagram/)
* [Sankey Diagram](https://gojs.net/latest/samples/sankey.html)
* [satwikkansal/wtfpython: Exploring Python through counter-intuitive snippets. If you think you know Python, think once more!](https://github.com/satwikkansal/wtfpython)
* [Search · mermaid](https://github.com/search?q=mermaid)
* [Serializing Entity Framework objects to JSON in ASP.NET Web API | StrathWeb. A free flowing web tech monologue.](https://www.strathweb.com/2012/03/serializing-entity-framework-objects-to-json-in-asp-net-web-api/)
* [Shared Context between Tests > xUnit.net](https://xunit.net/docs/shared-context.html)
* [Shell folder shortcuts - Windows CMD - SS64.com](https://ss64.com/nt/shell.html)
* [Slå på och stänga av tv:n med Google Home - Google Nest Hjälp](https://support.google.com/googlenest/answer/7498991?hl=sv&authuser=0)
* [Slurm Workload Manager - Overview](https://slurm.schedmd.com/overview.html)
* [SoCo/SoCo: SoCo (Sonos Controller) is a Python project that allows you to programmatically control Sonos speakers.](https://github.com/SoCo/SoCo)
* [Software | www.hpc2n.umu.se](https://www.hpc2n.umu.se/resources/software)
* [spacy-vis · spaCy Universe](https://spacy.io/universe/project/spacy-vis)
* [stanfordnlp/stanza: Official Stanford NLP Python Library for Many Human Languages](https://github.com/stanfordnlp/stanza)
* [Stanza - A Python NLP Library for Many Human Languages | Stanza](https://stanfordnlp.github.io/stanza/)
* [Static Site Generator | Nikola](https://getnikola.com/)
* [Statlig information i tv blir flerårigt forskningsprojekt - Nyheter (Ekot) | Sveriges Radio](https://sverigesradio.se/sida/artikel.aspx?programid=83&artikel=7372885)
* [Store, Action, Reducer Concepts Of Redux (Simplified)](https://www.thepieceoftech.com/2019/10/store-action-reducer-concepts-of-redux.html?fbclid=IwAR002sqfadQutJp-qEN7wKe9er9kEIpAQL4NE0EgAZiKOBIMBZXbyFptDbM)
* [StrathWeb. A free flowing web tech monologue.](https://www.strathweb.com/)
* [Support för Intelia Automatisk espressomaskin HD8751/11 | Saeco](https://www.philips.se/c-p/HD8751_11/saeco-intelia-automatisk-espressomaskin/kundtjanst)
* [SVG.js - Advent Calendar - a Collection by Ulrich-Matthias Schäfer on CodePen](https://codepen.io/collection/XpwMLO/)
* [Swedish Language Data Lab | AI](https://www.ai.se/en/projects-7/swedish-language-data-lab)
* [SwedPop – A national research infrastructure](http://swedpop.se/)
* [teambit/bit: Easily share components between projects, with your team. Compose UI applications together.](https://github.com/teambit/bit)
* [Tesseract.js | Pure Javascript OCR for 100 Languages!](https://tesseract.projectnaptha.com/)
* [Testing with InMemory - EF Core | Microsoft Docs](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory)
* [Text faces | Lenny face ( ͡° ͜ʖ ͡°), shrug face ¯\_(ツ)_/¯, look of disapproval ಠ_ಠ and more.](https://textfac.es/)
* [textpipe · spaCy Universe](https://spacy.io/universe/project/textpipe/)
* [tfidf nrmalize - Sök på Google](https://www.google.com/search?q=tfidf+nrmalize&ie=utf-8&oe=utf-8&aq=t&authuser=0)
* [thangchung/awesome-dotnet-core: A collection of awesome .NET core libraries, tools, frameworks and software](https://github.com/thangchung/awesome-dotnet-core)
* [The 100 Best Podcasts to Listen to Right Now (2020)](https://www.samuelthomasdavies.com/best-podcasts/)
* [The A.V. Club | Pop culture obsessives writing for the pop culture obsessed.](https://www.avclub.com/)
* [THE EMU SPEECH DATABASE MANAGEMENT SYSTEM (EMU-SDMS) | Raphael Winkelmann | 3 updates | Research Project](https://www.researchgate.net/project/The-EMU-Speech-Database-Management-System-EMU-SDMS)
* [The Google Home Commands Cheat Sheet](https://www.makeuseof.com/tag/google-home-commands-cheat-sheet/)
* [The Greatest Ever Infographic - Numberphile - YouTube](https://www.youtube.com/watch?v=3T7jMcstxY0)
* [The Scala Experience Safe Programming Can be Fun!](http://courses.cs.tau.ac.il/pyProg/1617a/lectures/12_MoreNumpy_ImageProcessing.pdf)
* [Tickets for DevSum 2020 - DevSum](https://www.devsum.se/tickets)
* [Tidyverse](https://www.tidyverse.org/learn/)
* [tir/test_coherencemodel.py at 17356762707471b4577880cf22f567202af5ab17 · simon-uni/tir](https://github.com/simon-uni/tir/blob/17356762707471b4577880cf22f567202af5ab17/lib/python3.5/site-packages/gensim/test/test_coherencemodel.py)
* [Top 10 VS Code Extensions for Software Developers - Level Up Coding](https://levelup.gitconnected.com/top-10-vs-code-extensions-for-software-developers-9c3a807c6656)
* [Top 10 Wireless Display Adapters of 2019 | Video Review](https://wiki.ezvid.com/best-wireless-display-adapters)
* [Top 100 C# Libraries 2019 - Google Kalkylark](https://docs.google.com/spreadsheets/d/1tCEbA1_CcvA8xXvsrKvAlG9MYo65_yo5z-UGd1DMLFs/edit#gid=0)
* [Top 5 Frameworks / React UI Component Libraries for 2019](https://devias.io/blog/top-5-react-ui-component-libraries-frameworks)
* [TOP IDE index](https://pypl.github.io/IDE.html)
* [Tracking Progress in Natural Language Processing | NLP-progress](http://nlpprogress.com/)
* [Trint: Automated Transcription of Audio and Video, Powered by AI](https://trint.com/?cn-reloaded=1)
* [tryck_matforradslista-2019.pdf](https://www.livsmedelsverket.se/globalassets/publikationsdatabas/folder/tryck_matforradslista-2019.pdf?AspxAutoDetectCookieSupport=1)
* [tuckerconnelly/rocketplate: Boilerplate for your next web project](https://github.com/tuckerconnelly/rocketplate)
* [TWC9: .NET Conf, .NET Core 3.0 RC1, Cascadia Code Font, Sega Genesis Mini and more | This Week On Channel 9 | Channel 9](https://channel9.msdn.com/Shows/This+Week+On+Channel+9/TWC9-NET-Conf-NET-Core-30-RC1-Cascadia-Code-Font-Sega-Genesis-Mini-and-more)
* [Type IPA phonetic symbols - online keyboard (all languages)](https://ipa.typeit.org/full/)
* [Usage - db-migrate](https://db-migrate.readthedocs.io/en/latest/Getting%20Started/usage/)
* [Using MALLET LDA to Learn Why Players Hate Pokémon Sword /Shield](https://towardsdatascience.com/using-mallet-lda-to-learn-why-players-hate-pok%C3%A9mon-sword-shield-23b12e4fc395?gi=db5d68193871)
* [Using MKL to boost Numpy performance on Ubuntu - Black Swan - Medium](https://medium.com/@black_swan/using-mkl-to-boost-numpy-performance-on-ubuntu-f62781e63c38)
* [Using ML.NET in Jupyter notebooks | Cesar de la Torre](https://devblogs.microsoft.com/cesardelatorre/using-ml-net-in-jupyter-notebooks/)
* [Vad-bör-du-ha-i-din-krislåda.pdf](https://www.civil.se/wp-content/blogs.dir/1/files/2017/04/Vad-b%c3%b6r-du-ha-i-din-krisl%c3%a5da.pdf)
* [Vagrant by HashiCorp](https://www.vagrantup.com/)
* [Van_Eyck_-_Arnolfini_Portrait.jpg (3087×4226)](https://upload.wikimedia.org/wikipedia/commons/3/33/Van_Eyck_-_Arnolfini_Portrait.jpg)
* [vidaXL Dumbbell Set 30kg - Hitta bästa pris på Prisjakt](https://www.prisjakt.nu/produkt.php?p=3120382)
* [Visual Studio Code Remote SSH Tips and Tricks](https://code.visualstudio.com/blogs/2019/10/03/remote-ssh-tips-and-tricks)
* [Visual Studio Online - Cloud IDE - Code Editor Online](https://visualstudio.microsoft.com/services/visual-studio-online/)
* [Visual Studio Online - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ms-vsonline.vsonline)
* [voila-dashboards/voila: Voilà turns Jupyter notebooks into standalone web applications](https://github.com/voila-dashboards/voila)
* [Vue CLI 3: A Game Changer for Frontend Development - DZone Web Dev](https://dzone.com/articles/vue-cli-3-a-game-changer-for-frontend-development)
* [ward clustering python - Sök på Google](https://www.google.com/search?q=ward%20clustering%20python&ie=utf-8&oe=utf-8&aq=t&authuser=0)
* [Ways to Compute Topics over Time, Part 1 · From Data to Scholarship](https://jeriwieringa.com/2017/06/21/Calculating-and-Visualizing-Topic-Significance-over-Time-Part-1/)
* [Welcome to Click — Click Documentation (8.x)](https://click.palletsprojects.com/en/master/)
* [What `R` you? (R list in python) | R-bloggers](https://www.r-bloggers.com/what-r-you-r-list-in-python/)
* [What does Judaism say about Christmas: A night we don't study, a day soaked in sorrows, and today's materialism HQ in progress](https://www.sefaria.org/sheets/51928.2?lang=bi)
* [What Every C#/.Net Developer Needs to Know in 2019 - DZone Web Dev](https://dzone.com/articles/what-every-cnet-developer-need-to-know-in-2019)
* [Why this creepy melody is in so many movies - YouTube](https://www.youtube.com/watch?v=-3-bVRYRnSM)
* [Xamarin | Open-source mobile app platform for .NET](https://dotnet.microsoft.com/apps/xamarin)
* [Xming X Server for Windows - Official Website](http://www.straightrunning.com/XmingNotes/)
* [XPlot - F# Data Visualization Package](https://fslab.org/XPlot/)
* [You can now try Microsoft’s web-based version of Visual Studio | TechCrunch](https://techcrunch.com/2019/11/04/you-can-now-try-microsofts-web-based-version-of-visual-studio/)

* [(46) Maximum Likelihood For the Normal Distribution, step-by-step! - YouTube](https://www.youtube.com/watch?v=Dn6b9fCIUpM)
* [Best practices for writing Dockerfiles | Docker Documentation](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)
* [Minimal Ubuntu, on public clouds and Docker Hub | Ubuntu](https://ubuntu.com/blog/minimal-ubuntu-released)
* [Google Developers](https://developers.google.com/products/?hl=en)
* [ML Universal Guides  |  Google Developers](https://developers.google.com/machine-learning/guides/)
* [The Twelve-Factor App](https://12factor.net/processes)

